name: Deploy with Conjur

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch secrets from Conjur
        uses: cyberark/conjur-action@v2
        with:
          url: https://localhost:443
          authn_id: github-keerth124
          host_id: data/github-apps/keerth124/ABCStore
          secrets: |
            data/vault/example/safe/test-secret|TEST_SECRET

      - name: Use fetched secret
        run: ./deploy.sh
        env:
          TEST_SECRET: ${{ env.TEST_SECRET }}
