platform: github
org: keerth124
tenant: 
conjur_url: https://localhost:443
conjur_target: self-hosted
workload_auth: jwt
provisioning_mode: bootstrap
authenticator_name: github-keerth124
audience: conjur-cloud
workload_count: 27
