package core

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const generatedGitignore = `# Generated by conjur-onboard.
# Keep runtime credentials and live token captures out of source control.
*token*
*secret*
*credential*
apply-log*.json
validate-log*.json
`

// EnsureWorkDir creates a COT working directory and writes baseline hygiene files.
func EnsureWorkDir(path string) (string, error) {
	if path == "" {
		return "", fmt.Errorf("work directory is empty")
	}

	clean := filepath.Clean(path)
	if err := os.MkdirAll(clean, 0o755); err != nil {
		return "", fmt.Errorf("creating %s: %w", clean, err)
	}

	gitignorePath := filepath.Join(clean, ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := writeFileAtomic(gitignorePath, []byte(generatedGitignore), 0o644); err != nil {
			return "", err
		}
	} else if err != nil {
		return "", fmt.Errorf("checking %s: %w", gitignorePath, err)
	}

	return clean, nil
}

// WriteJSON writes stable, pretty-printed JSON to dir/name.
func WriteJSON(dir, name string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling %s: %w", name, err)
	}
	data = append(data, '\n')
	return WriteFile(dir, name, data)
}

// WriteText writes UTF-8 text to dir/name using an atomic replace.
func WriteText(dir, name, value string) error {
	return WriteFile(dir, name, []byte(value))
}

// WriteFile writes bytes to dir/name using an atomic replace.
func WriteFile(dir, name string, data []byte) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	return writeFileAtomic(filepath.Join(dir, name), data, 0o644)
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file for %s: %w", path, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("writing temp file for %s: %w", path, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		return fmt.Errorf("chmod temp file for %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing temp file for %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("replacing %s: %w", path, err)
	}
	return nil
}
