package conjur

import (
	"fmt"
	"path/filepath"

	"github.com/cyberark/conjur-onboard/internal/core"
)

// writeAuthenticatorBranchArtifact writes the parent branch required by the
// self-hosted authenticator creation API.
func writeAuthenticatorBranchArtifact(cfg GenerateConfig) error {
	body := "# Generated by conjur-onboard - do not hand-edit.\n\n- !policy\n  id: conjur/authn-jwt\n"
	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "00-authenticator-branch.yml", body); err != nil {
		return fmt.Errorf("writing authenticator branch artifact: %w", err)
	}
	return nil
}

func removeAuthenticatorBranchArtifact(workDir string) error {
	return removeAPIArtifact(workDir, "00-authenticator-branch.yml", "stale authenticator branch artifact")
}
