package conjur

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/cyberark/conjur-onboard/internal/core"
)

// writeAuthenticatorBranchArtifact writes the parent branch required by the
// self-hosted authenticator creation API.
func writeAuthenticatorBranchArtifact(cfg GenerateConfig) error {
	body := "# Generated by conjur-onboard - do not hand-edit.\n\n- !policy\n  id: conjur/authn-jwt\n"
	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "00-authenticator-branch.yml", body); err != nil {
		return fmt.Errorf("writing authenticator branch artifact: %w", err)
	}
	return nil
}

func removeAuthenticatorBranchArtifact(workDir string) error {
	return removeAPIArtifact(workDir, "00-authenticator-branch.yml", "stale authenticator branch artifact")
}

func writeIdentityBranchArtifact(identityPath string, cfg GenerateConfig) error {
	parent, leaf, err := identityPathParentLeaf(identityPath)
	if err != nil {
		return err
	}
	_ = parent
	body := fmt.Sprintf("# Generated by conjur-onboard - do not hand-edit.\n\n- !policy\n  id: %s\n", leaf)
	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "02-identity-branch.yml", body); err != nil {
		return fmt.Errorf("writing identity branch artifact: %w", err)
	}
	return nil
}

func removeIdentityBranchArtifact(workDir string) error {
	return removeAPIArtifact(workDir, "02-identity-branch.yml", "stale identity branch artifact")
}

func identityPathParentLeaf(identityPath string) (string, string, error) {
	parts := splitPolicyPath(identityPath)
	if len(parts) < 2 {
		return "", "", fmt.Errorf("identity path %q must include a parent and leaf policy", identityPath)
	}
	parent := strings.Join(parts[:len(parts)-1], "/")
	leaf := parts[len(parts)-1]
	return parent, leaf, nil
}

func splitPolicyPath(value string) []string {
	raw := strings.Split(strings.Trim(value, "/"), "/")
	parts := make([]string, 0, len(raw))
	for _, part := range raw {
		part = strings.TrimSpace(part)
		if part != "" {
			parts = append(parts, part)
		}
	}
	return parts
}
