package conjur

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/cyberark/conjur-onboard/internal/core"
)

// writeAuthenticatorBranchArtifact writes the parent branch required by the
// self-hosted authenticator creation API.
func writeAuthenticatorBranchArtifact(cfg GenerateConfig) error {
	body := "# Generated by conjur-onboard - do not hand-edit.\n\n- !policy\n  id: conjur/authn-jwt\n"
	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "00-authenticator-branch.yml", body); err != nil {
		return fmt.Errorf("writing authenticator branch artifact: %w", err)
	}
	return nil
}

func removeAuthenticatorBranchArtifact(workDir string) error {
	return removeAPIArtifact(workDir, "00-authenticator-branch.yml", "stale authenticator branch artifact")
}

func writeIdentityBranchArtifact(identityPath string, cfg GenerateConfig) error {
	base, branches, err := identityBranchBaseAndChain(identityPath)
	if err != nil {
		return err
	}
	_ = base

	var sb strings.Builder
	sb.WriteString("# Generated by conjur-onboard - do not hand-edit.\n\n")
	writeNestedPolicyChain(&sb, branches, 0)

	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "02-identity-branch.yml", sb.String()); err != nil {
		return fmt.Errorf("writing identity branch artifact: %w", err)
	}
	return nil
}

func removeIdentityBranchArtifact(workDir string) error {
	return removeAPIArtifact(workDir, "02-identity-branch.yml", "stale identity branch artifact")
}

func identityBranchBaseAndChain(identityPath string) (string, []string, error) {
	parts := splitPolicyPath(identityPath)
	if len(parts) < 2 {
		return "", nil, fmt.Errorf("identity path %q must include a base policy and at least one child policy", identityPath)
	}
	return parts[0], parts[1:], nil
}

func writeNestedPolicyChain(sb *strings.Builder, parts []string, indent int) {
	if len(parts) == 0 {
		return
	}

	prefix := strings.Repeat(" ", indent)
	sb.WriteString(prefix + "- !policy\n")
	sb.WriteString(fmt.Sprintf("%s  id: %s\n", prefix, parts[0]))
	if len(parts) > 1 {
		sb.WriteString(prefix + "  body:\n")
		writeNestedPolicyChain(sb, parts[1:], indent+4)
	}
}

func splitPolicyPath(value string) []string {
	raw := strings.Split(strings.Trim(value, "/"), "/")
	parts := make([]string, 0, len(raw))
	for _, part := range raw {
		part = strings.TrimSpace(part)
		if part != "" {
			parts = append(parts, part)
		}
	}
	return parts
}
