package conjur

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cyberark/conjur-onboard/internal/core"
)

// GroupMemberBody is the JSON body for POST /api/groups/{id}/members.
type GroupMemberBody struct {
	ID   string `json:"id"`
	Kind string `json:"kind"`
}

// writeGroupMembersArtifact writes 03-add-group-members.jsonl.
// Each line is a JSON object suitable as the body for a single membership addition.
func writeGroupMembersArtifact(authnName string, hosts []WorkloadHost, cfg GenerateConfig) (string, error) {
	groupID := appsGroupID(authnName)

	var sb strings.Builder
	for _, h := range hosts {
		entry := GroupMemberBody{
			ID:   h.FullPath,
			Kind: "workload",
		}
		data, err := json.Marshal(entry)
		if err != nil {
			return "", fmt.Errorf("encoding group member: %w", err)
		}
		sb.Write(data)
		sb.WriteByte('\n')
	}

	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "03-add-group-members.jsonl", sb.String()); err != nil {
		return "", fmt.Errorf("writing group members artifact: %w", err)
	}
	return groupID, nil
}

func removeGroupMembersArtifact(workDir string) error {
	path := filepath.Join(workDir, "api", "03-add-group-members.jsonl")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing stale group members artifact: %w", err)
	}
	return nil
}

func writeAuthenticatorGrantPolicyArtifact(authnName string, groupID string, hosts []WorkloadHost, cfg GenerateConfig) error {
	var sb strings.Builder
	sb.WriteString("# Generated by conjur-onboard - do not hand-edit.\n")
	sb.WriteString("# Self-hosted fallback for environments without group membership REST endpoints.\n\n")
	sb.WriteString("- !grant\n")
	sb.WriteString(fmt.Sprintf("  role: !group %s\n", authenticatorAppsGroupPath(authnName)))
	sb.WriteString("  members:\n")
	for _, h := range hosts {
		sb.WriteString(fmt.Sprintf("    - !host %s\n", h.FullPath))
	}

	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "04-grant-authenticator-access.yml", sb.String()); err != nil {
		return fmt.Errorf("writing authenticator grant policy artifact: %w", err)
	}
	return nil
}

func removeAuthenticatorGrantPolicyArtifact(workDir string) error {
	path := filepath.Join(workDir, "api", "04-grant-authenticator-access.yml")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing stale authenticator grant policy artifact: %w", err)
	}
	return nil
}

func authenticatorAppsGroupPath(authnName string) string {
	return fmt.Sprintf("conjur/authn-jwt/%s/apps", authnName)
}
