package conjur

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cyberark/conjur-onboard/internal/core"
	"github.com/cyberark/conjur-onboard/internal/platform"
)

// writeWorkloadPolicyArtifact writes 02-workloads.yml.
func writeWorkloadPolicyArtifact(identityPath string, workloads []platform.Workload, cfg GenerateConfig) error {
	var sb strings.Builder
	sb.WriteString("# Generated by conjur-onboard - do not hand-edit.\n")
	sb.WriteString(fmt.Sprintf("# Load via: POST %s\n\n", policyRootPath(cfg.ConjurTarget)))
	sb.WriteString("- !policy\n")
	sb.WriteString(fmt.Sprintf("  id: %s\n", identityPath))
	sb.WriteString("  body:\n")

	for _, h := range workloads {
		sb.WriteString("    - !host\n")
		sb.WriteString(fmt.Sprintf("      id: %s\n", h.HostID))
		writeAnnotations(&sb, h.Annotations)
	}

	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := core.WriteText(destDir, "02-workloads.yml", sb.String()); err != nil {
		return fmt.Errorf("writing workloads YAML: %w", err)
	}

	return nil
}

func writeAnnotations(sb *strings.Builder, annotations map[string]string) {
	if len(annotations) == 0 {
		return
	}
	keys := make([]string, 0, len(annotations))
	for key := range annotations {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	sb.WriteString("      annotations:\n")
	for _, key := range keys {
		sb.WriteString(fmt.Sprintf("        %s: %s\n", key, annotations[key]))
	}
}

func jwtAnnotationKey(authnName string, claim string) string {
	return fmt.Sprintf("authn-jwt/%s/%s", authnName, claim)
}
