package conjur

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	ghdisc "github.com/cyberark/conjur-onboard/internal/github"
)

// WorkloadHost represents a single !host entry in the policy YAML.
type WorkloadHost struct {
	FullPath string // e.g. "data/github-apps/acme-corp/acme-corp/api-service"
	HostID   string // relative to the policy branch, e.g. "acme-corp/api-service"
}

// buildWorkloads returns the list of workload hosts to create based on discovery.
func buildWorkloads(disc *ghdisc.DiscoveryResult) []WorkloadHost {
	identPath := identityPath(disc.Org)
	var hosts []WorkloadHost

	for _, repo := range disc.Repos {
		// Base workload for the repo.
		hosts = append(hosts, WorkloadHost{
			FullPath: workloadID(identPath, repo.FullName, ""),
			HostID:   repo.FullName,
		})
		// Per-environment workloads when environments are configured.
		for _, env := range repo.Environments {
			hosts = append(hosts, WorkloadHost{
				FullPath: workloadID(identPath, repo.FullName, env),
				HostID:   repo.FullName + "/" + env,
			})
		}
	}
	return hosts
}

// writeWorkloadPolicyArtifact writes 02-workloads.yml.
func writeWorkloadPolicyArtifact(disc *ghdisc.DiscoveryResult, cfg GenerateConfig) ([]WorkloadHost, error) {
	hosts := buildWorkloads(disc)
	identPath := identityPath(disc.Org)

	var sb strings.Builder
	sb.WriteString("# Generated by conjur-onboard — do not hand-edit.\n")
	sb.WriteString("# Load via: POST /policies/conjur/policy/root\n\n")
	sb.WriteString("- !policy\n")
	sb.WriteString(fmt.Sprintf("  id: %s\n", identPath))
	sb.WriteString("  body:\n")

	for _, h := range hosts {
		sb.WriteString(fmt.Sprintf("    - !host\n"))
		sb.WriteString(fmt.Sprintf("      id: %s\n", h.HostID))
	}

	destDir := filepath.Join(cfg.WorkDir, "api")
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return nil, fmt.Errorf("creating api dir: %w", err)
	}

	path := filepath.Join(destDir, "02-workloads.yml")
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		return nil, fmt.Errorf("writing workloads YAML: %w", err)
	}

	return hosts, nil
}
